=== ClickTravel-VincentCleaver/Cheddar/cheddar/cheddar-cdm/src/main/xsd/tactical/common.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.clicktravel.com/schema/v1/common"
	xmlns:common="http://www.clicktravel.com/schema/v1/common"
	elementFormDefault="qualified">

	<element name="ErrorResponse">
		<complexType>
			<choice>
				<element name="errors" type="common:Error" maxOccurs="unbounded" />
				<element name="validationErrors" type="common:ValidationError"
					maxOccurs="unbounded" />
			</choice>
		</complexType>
	</element>

	<complexType name="Error">
		<sequence>
			<element name="description" type="string" />
		</sequence>
	</complexType>

	<complexType name="ValidationError">
		<sequence>
			<element name="field" type="string" maxOccurs="unbounded"/>
			<element name="error" type="string" />
		</sequence>
	</complexType>
	
</schema>

=== ClickTravel-VincentCleaver/Cheddar/cheddar/cheddar-cdm/src/test/xsd/tactical/ErrorResponse_validationErrors.xml
<?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.clicktravel.com/schema/v1/common"
	xsi:schemaLocation="http://www.clicktravel.com/schema/v1/common ../../../main/xsd/tactical/common.xsd">

	<validationErrors>
		<field>ownerEmail</field>
		<error>The field is empty</error>
	</validationErrors>
	<validationErrors>
		<field>ownerEmail</field>
		<error>The field is not a valid email address</error>
	</validationErrors>
	<validationErrors>
		<field>ownerTitle</field>
		<field>ownerLastName</field>
		<error>Title or Last name must not be blank</error>
	</validationErrors>

</ErrorResponse>
